#%RAML 1.0 DataType
    type: object
    additionalProperties: false
    properties:
      networkControl: 
        type: object
        properties:
          transactionLocator:
            type: string
          transactionOriginator:
            type: string
          messageOriginator:
            type: string
          messageDestination:
            type: string
      conversionExceptions?: !include /Datatypes/Fragments/conversionException.raml
      warnings?: !include /Datatypes/Fragments/warnings.raml
      exceptions?: !include /Datatypes/Fragments/exceptions.raml
      vin?:
        type: string
      csotCode?:
        type: string
      recordMatchSequenceId?:
        type: string
      jurisdictionVehicle?: !include /Datatypes/Fragments/jurisdictionVehicleUnsolicited.raml

