http-listener:
  host: "0.0.0.0"
  port: "8082"
  path: "/api/*"
  read-timeout: "30000"
  keystores:
   type: "JKS"
   path: "keystores/keystore.jks"
   password: "Mule@#2022"
  
  
nmvtis-sf-solicited-sapi:
  host: "nmvtis-sf-solicited-sapi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  newVehicleInquiryPath: "/v1/NewVehicleInquiry"
  usedVehicleInquiryPath: "/v1/UsedVehicleInquiry"
  addTitlePath: "/v1/AddTitle"
  removeTitlePath: "/v1/RemoveTitle"
  undoChangeJurisdictionOfTitlePath: "/v1/UndoChangeJurisdictionOfTitle"
  changeJurisdictionOfTitlePath: "/v1/ChangeJurisdictionOfTitle"
  addBrandPath: "/v1/AddBrand"
  removeBrandPath: "/v1/RemoveBrand"
  transferOrChangeTitlePath: "/v1/TransferOrChangeTitle"
  brandInquiryPath: "/v1/BrandInquiry"
  purgeTitlePath: "/v1/PurgeTitle"
  undoTransferOrChangeTitlePath: "/v1/UndoTransferOrChangeTitle"
  vehicleHistoryInquirypath: "/v1/VehicleHistoryInquiry"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-sf-unsolicited-sapi:
  host: "nmvtis-sf-unsolicited-sapi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  stateVehicleDataResponsePath: "/v1/StateVehicleDataResponse"
  undoCsotNotificationResponsePath: "/v1/UndoCsotNotificationResponse"
  OldJurisdictionVehicleResponsePath: "/v1/OldJurisdictionVehicleResponse"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"