errors:
  error-code-400: "BAD_REQUEST"
  error-code-404: "NOT_FOUND"
  error-code-405: "METHOD_NOT_ALLOWED"
  error-code-406: "NOT_ACCEPTABLE"
  error-code-408: "CONNECTIVITY"
  error-code-415: "UNSUPPORTED_MEDIA_TYPE"
  error-code-500: "INTERNAL_SERVER_ERROR"
  error-code-501: "NOT_IMPLEMENTED"
  error-code-wsc: "WSC:CANNOT_DISPATCH"
  error-code-502: "HTTP:CONNECTIVITY"
  error-code-401: "HTTP:UNAUTHORIZED"
  error-code-429: "HTTP:TOO_MANY_REQUESTS"
  error-code-503: "HTTP:SERVICE_UNAVAILABLE"
  error-code-wsc-connectivity: "WSC:CONNECTIVITY"
  error-code-db-connectivity-500: "DB:CONNECTIVITY"
  error-code-db-400: "BAD_SQL_SYNTAX"
  error-code-db-query-execution-500: "DB:QUERY_EXECUTION"
  error-code-db-retry-exhausted-503: "DB:RETRY_EXHAUSTED"
  error-code-stream-exceeded-500: "STREAM_MAXIMUM_SIZE_EXCEEDED"