http-listener:
  host: "0.0.0.0"
  port: "8087"
  path: "/api/*"
  read-timeout: "30000"
  keystores:
   type: "JKS"
   path: "keystores/keystore.jks"
   password: "Mule@#2022"
  
  
nmvtis-new-vehicle-inquiry-papi:
  host: "nmvtis-new-vehicle-inquiry-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/NewVehicleInquiry"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-used-vehicle-inquiry-papi:
  host: "nmvtis-used-vehicle-inquiry-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/UsedVehicleInquiry"
  unsolicited-path: "/v1/StateVehicleDataResponse"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-add-title-papi:
  host: "nmvtis-add-title-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/AddTitle"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-remove-title-papi:
  host: "nmvtis-remove-title-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/RemoveTitle"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-undo-change-jurisdiction-of-title-papi:
  host: "nmvtis-undo-csot-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/UndoChangeJurisdictionOfTitle"
  unsolicited-undo-csot-response-path: "/v1/UndoCsotNotificationResponse"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-change-jurisdiction-of-title-papi:
  host: "nmvtis-csot-papi.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/ChangeJurisdictionOfTitle"
  unsol-old-jurisdiction-path: "/v1/OldJurisdictionVehicleResponse"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-add-brand-papi:
  host: "nmvtis-add-brand-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/AddBrand"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"
  
nmvtis-remove-brand-papi:
  host: "nmvtis-remove-brand-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/RemoveBrand"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-instate-title-transfer-papi:
  host: "nmvtis-instate-title-transfer-papi.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/TransferOrChangeTitle"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-brand-inquiry-papi:
  host: "nmvtis-brand-inquiry-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/BrandInquiry"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-purge-title-papi:
  host: "nmvtis-purge-title-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/PurgeTitle"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-undo-instate-title-transfer-papi:
  host: "nmvtis-undo-instate-title-transfer-papi.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/UndoTransferOrChangeTitle"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"

nmvtis-vehicle-history-inquiry-papi:
  host: "nmvtis-vehicle-history-inquiry-papi-dev.us-e1.cloudhub.io"
  port: "443"
  method: "POST"
  protocol: "HTTPS"
  basepath: "/api"
  path: "/v1/VehicleHistoryInquiry"
  appname: ""
  reconnection-frequency: "2000"
  reconnection-attempts: "1" 
  response-timeout: "120000"
  connection-idle-timeout: "120000"