#%RAML 1.0
title:  nmvits routing api
baseUri: /api
description: Route request to AAMVA and receive a response from AAMVA
version: v1
protocols: [HTTPS]
mediaType: 
- application/json


/v1/NewVehicleInquiry:
  post:
    displayName: Send NewVehicleInquiry Request to AAMVA-NMVTIS

/v1/NewVehicleInquiryResponse:
  post:
    displayName: Recieve NewVehicleInquiry Response from AAMVA-NMVTIS

/v1/UsedVehicleInquiry:
  post:
    displayName: Send UsedVehicleInquiry Request to AAMVA-NMVTIS

/v1/UsedVehicleInquiryResponse:
  post:
    displayName: Recieve UsedVehicleInquiry Response from AAMVA-NMVTIS

/v1/StateVehicleDataRequest:
  post:
    displayName: Recieve unsolicited State Vehicle data request from AAMVA.

/v1/StateVehicleDataResponse:
  post:
    displayName: Send unsolicited State Vehicle Response to AAMVA-NMVTIS.

/v1/AddTitle:
  post:
    displayName: Send Add Title Request to AAMVA-NMVTIS.

/v1/AddTitleResponse:
  post:
    displayName: Recieve Add Title Response from AAMVA-NMVTIS.

/v1/RemoveTitle:
  post:
    displayName: Send Remove Title Request to AAMVA-NMVTIS.

/v1/RemoveTitleResponse:
  post:
    displayName: Recieve Remove Title Response from AAMVA-NMVTIS.

/v1/UndoChangeJurisdictionOfTitle:
  post:
    displayName: Send Undo Change Jurisdiction Of Title Request to AAMVA-NMVTIS

/v1/UndoChangeJurisdictionOfTitleResponse:
  post:
    displayName: Recieve Undo Change Jurisdiction Of Title Response from AAMVA-NMVTIS

/v1/UndoCSOTRequest:
  post:
    displayName: Recieve Unsolicited CSOT Undo Notification Request from AAMVA-NMVTIS

/v1/UndoCsotNotificationResponse:
  post:
    displayName: Send Unsolicited CSOT Undo Notification Response to AAMVA-NMVTIS

/v1/ChangeJurisdictionOfTitle:
  post:
    displayName: Send Change Jurisdiction Of Title Request to AAMVA-NMVTIS

/v1/ChangeJurisdictionOfTitleResponse:
  post:
    displayName: Recieve Change Jurisdiction Of Title Response from AAMVA-NMVTIS

/v1/TransferOrChangeTitle:
  post:
    displayName: Recieve InState Title Transfer Request from AAMVA-NMVTIS

/v1/TransferOrChangeTitleResponse:
  post:
    displayName: Recieve InState Title Transfer Response from AAMVA-NMVTIS

/v1/MovedToHistoryNotice:
  post:
    displayName: Recieve Unsolicited Moved To History Notice Notification Response from AAMVA-NMVTIS

/v1/MovedToCurrentNotice:
  post:
    displayName: Recieve Unsolicited Moved To Current Notice Notification Response from AAMVA-NMVTIS

/v1/OldJurisdictionVehicleRequest:
  post:
    displayName: Recieve Unsolicited Old Jurisdiction Vehicle Request from AAMVA-NMVTIS

/v1/OldJurisdictionVehicleResponse:
  post:
    displayName: Recieve Unsolicited Old Jurisdiction Vehicle Response from AAMVA-NMVTIS.

/v1/AddBrand:
  post:
    displayName: Send Add Brand Request to AAMVA-NMVTIS.

/v1/AddBrandResponse:
  post:
    displayName: Recieve Add Brand Response from AAMVA-NMVTIS.

/v1/ReceiveDuplicateNotice:
  post:
    displayName: Recieve Unsolicited Duplicate Notice Notification Response from AAMVA-NMVTIS

/v1/ReceiveDuplicateResolvedNotice:
  post:
    displayName: Recieve Unsolicited Duplicate Resolved Notice Notification Response from AAMVA-NMVTIS

/v1/BrandInquiry:
  post:
    displayName: Send Brand Inquiry Request to AAMVA-NMVTIS.

/v1/BrandInquiryResponse:
  post:
    displayName: Recieve Brand Inquiry Response from AAMVA-NMVTIS

/v1/PurgeTitle:
  post:
    displayName: Send Purge Title Request to AAMVA-NMVTIS.

/v1/PurgeTitleResponse:
  post:
    displayName: Recieve Purge Title Response from AAMVA-NMVTIS.

/v1/UndoTransferOrChangeTitle:
  post:
    displayName: Send Undo Instate Title Transfer Request to AAMVA-NMVTIS.

/v1/UndoTransferOrChangeTitleResponse:
  post:
    displayName: Recieve Undo Instate Title Transfer Response from AAMVA-NMVTIS.

/v1/VehicleHistoryInquiry:
  post:
    displayName: Send Vehicle History Inquiry Request to AAMVA-NMVTIS.

/v1/VehicleHistoryResponse:
  post:
    displayName: Recieve Vehicle History Inquiry Response from AAMVA-NMVTIS.

/v1/OldJurisdictionVehicleErrorResponse:
  post:
    displayName: Recieve Unsolicited Old Jurisdiction Vehicle Error Response from AAMVA-NMVTIS

/v1/Authentication:
  get:
    displayName: Generates AAMVA authentication token.

/v1/Verification:
  post:
    displayName: The authentication token will be verified by this verification service.

/v1/UndoCSOTErrorResponse:
  post:
    displayName: Recieve Unsolicited Undo CSOT Error Response from AAMVA-NMVTIS

/v1/ChangeJurisdictionOfTitleOldVehicleResponse:
  post:
    displayName: Recieve Change Jurisdiction Of Title Old Vehicle Response from AAMVA-NMVTIS.

/v1/RemoveBrand:
  post:
    displayName: Send Remove Brand Request to AAMVA-NMVTIS.

/v1/RemoveBrandResponse:
  post:
    displayName: Recieve Remove Brand Response from AAMVA-NMVTIS.
