#%RAML 1.0 DataType
    type: object
    properties:
      makeCode?:
        type: string | nil
      modelYear?:
        type: number | nil
      odometer?: !include odometer.raml
      odometerReadingDate?:
        type: string | nil
      gvwr?:
        type: string | nil
      grossLadenSumWeight?:
        type: string | nil
      unladenWeight?:
        type: string | nil
      axleQuantity?:
        type: number | nil
      doorQuantity?:
        type: number | nil
      cylinderQuantity?:
        type: number | nil
      useCode?:
        type: string | nil
      fuelTypeCode?:
        type: string | nil
      newCode?:
        type: string | nil
      secondaryColor?:
        type: string | nil
      primaryColor?:
        type: string | nil
      modelDescription?:
        type: string | nil
      bodyStyleCode?:
        type: string | nil
      seriesModelCode?:
        type: string | nil
      modelCode?:
        type: string | nil
      bodyCategoryCode?:
        type: string | nil
      isRental?:
        type: boolean | nil
      isLease?:
        type: boolean | nil
      lienQuantity?:
        type: number | nil
      ownerAppliedId?:
        type: string | nil
      vinIssuer?:
        type: string | nil